import Head from "next/head";
import React, { useState, useEffect } from "react";
import { ethers } from "ethers";
import { CoffeeContractAddress } from "../config";
import CoffeeAbi from "../utils/Coffee.json";
import Buy from "../components/Buy";
import Memos from "../components/Memos";
import Navbar from "../components/Navbar";

export default function Home() {
  const [state, setState] = useState({
    provider: null,
    signer: null,
    contract: null,
  });

  const [account, setAccount] = useState("Not Connected");
  useEffect(() => {
    const connectWallet = async () => {
      const contractAbi = CoffeeAbi.abi;
      try {
        const { ethereum } = window;
        if (ethereum) {
          const account = await ethereum.request({
            method: "eth_requestAccounts",
          });
          window.ethereum.on("chainChange", () => {
            window.location.reload();
          });

          window.ethereum.on("accountChange", () => {
            window.location.reload();
          });
          const provider = new ethers.providers.Web3Provider(ethereum);
          const signer = provider.getSigner();
          const contract = new ethers.Contract(
            CoffeeContractAddress,
            contractAbi,
            signer
          );
          setAccount(account);
          setState({ provider, signer, contract });
        } else {
          alert("Please install metamask");
        }
      } catch (error) {
        console.log(error.message);
      }
    };
    connectWallet();
  }, []);
  return (
    <>
      <Head>
        <title>BuyMeCoffee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <h1 className="text-3xl capitalize text-center p-5 font-mono">
          Buy Me A Coffee ☕
        </h1>
        <h3 className="text-xl capitalize text-center p-3">
          Welcome {account}
        </h3>
        <Buy state={state} />
        <Memos state={state} />
      </main>
    </>
  );
}
